//
// ConnectionStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

/** The status of a ``Connection``. */
public enum ConnectionStatus: String, Sendable, Codable, CaseIterable {
    case disconnected = "disconnected"
    case connecting = "connecting"
    case connected = "connected"
    case disconnecting = "disconnecting"
}
