//
// CustomModule.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

/** A type-erased ``Module`` for encoding external implementations. */
public struct CustomModule: Sendable, Codable, Hashable {

    public var innerType: ModuleType
    public var json: JSON

    public init(innerType: ModuleType, json: JSON) {
        self.innerType = innerType
        self.json = json
    }
}

