//
// DNSModuleDomainPolicy.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

public enum DNSModuleDomainPolicy: String, Sendable, Codable, CaseIterable {
    case match = "match"
    case matchAndSearch = "matchAndSearch"
}
