//
// DNSModuleProtocolTypeTls.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

public struct DNSModuleProtocolTypeTls: Sendable, Codable, Hashable {

    public enum ModelType: String, Sendable, Codable, CaseIterable {
        case tls = "tls"
    }
    public var type: ModelType
    public var hostname: String

    public init(type: ModelType, hostname: String) {
        self.type = type
        self.hostname = hostname
    }
}

