//
// DNSModuleProtocolTypeHttps.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

public struct DNSModuleProtocolTypeHttps: Sendable, Codable, Hashable {

    public enum ModelType: String, Sendable, Codable, CaseIterable {
        case https = "https"
    }
    public var type: ModelType
    public var url: URL

    public init(type: ModelType, url: URL) {
        self.type = type
        self.url = url
    }
}

