//
// DNSModule.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

/** DNS settings. */
public struct DNSModule: Sendable, Codable, Hashable {

    public var id: UniqueID
    public var protocolType: DNSModuleProtocolType
    public var servers: [Address]
    public var domainName: Address?
    public var searchDomains: [Address]?
    public var inheritsVPN: Bool?
    public var domainPolicy: DNSModuleDomainPolicy?
    public var routesThroughVPN: Bool?

    public init(id: UniqueID, protocolType: DNSModuleProtocolType, servers: [Address], domainName: Address? = nil, searchDomains: [Address]? = nil, inheritsVPN: Bool? = nil, domainPolicy: DNSModuleDomainPolicy? = nil, routesThroughVPN: Bool? = nil) {
        self.id = id
        self.protocolType = protocolType
        self.servers = servers
        self.domainName = domainName
        self.searchDomains = searchDomains
        self.inheritsVPN = inheritsVPN
        self.domainPolicy = domainPolicy
        self.routesThroughVPN = routesThroughVPN
    }
}

