//
// HTTPProxyModule.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

/** HTTP proxy settings. */
public struct HTTPProxyModule: Sendable, Codable, Hashable {

    public var id: UniqueID
    public var proxy: Endpoint?
    public var secureProxy: Endpoint?
    public var pacURL: URL?
    public var bypassDomains: [Address]

    public init(id: UniqueID, proxy: Endpoint? = nil, secureProxy: Endpoint? = nil, pacURL: URL? = nil, bypassDomains: [Address]) {
        self.id = id
        self.proxy = proxy
        self.secureProxy = secureProxy
        self.pacURL = pacURL
        self.bypassDomains = bypassDomains
    }
}

