//
// IPModule.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

/** IP and routes. */
public struct IPModule: Sendable, Codable, Hashable {

    public var id: UniqueID
    public var ipv4: IPSettings?
    public var ipv6: IPSettings?
    public var mtu: Int?

    public init(id: UniqueID, ipv4: IPSettings? = nil, ipv6: IPSettings? = nil, mtu: Int? = nil) {
        self.id = id
        self.ipv4 = ipv4
        self.ipv6 = ipv6
        self.mtu = mtu
    }
}

