//
// IPSettings.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

/** IP settings and routes. */
public struct IPSettings: Sendable, Codable, Hashable {

    /** The subnets. */
    public var subnets: [Subnet]
    /** The included routes. */
    public var includedRoutes: [Route]
    /** The excluded routes. */
    public var excludedRoutes: [Route]

    public init(subnets: [Subnet], includedRoutes: [Route], excludedRoutes: [Route]) {
        self.subnets = subnets
        self.includedRoutes = includedRoutes
        self.excludedRoutes = excludedRoutes
    }
}

