//
// IPSocketType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

/** A socket type with optional info about the IP endpoint. */
public enum IPSocketType: String, Sendable, Codable, CaseIterable {
    /// UDP socket type.
    case udp = "UDP"
    /// TCP socket type.
    case tcp = "TCP"
    /// UDP socket type (IPv4).
    case udp4 = "UDP4"
    /// TCP socket type (IPv4).
    case tcp4 = "TCP4"
    /// UDP socket type (IPv6).
    case udp6 = "UDP6"
    /// TCP socket type (IPv6).
    case tcp6 = "TCP6"
}
