//
// ModuleType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

/** Raw type univocally associated to each ``Module`` implementation. */
public enum ModuleType: String, Sendable, Codable, CaseIterable {
    case Custom = "Custom"
    case DNS = "DNS"
    case HTTPProxy = "HTTPProxy"
    case IP = "IP"
    case OnDemand = "OnDemand"
    case OpenVPN = "OpenVPN"
    case Provider = "Provider"
    case WireGuard = "WireGuard"
    case Undefined = "Undefined"
}
