//
// OnDemandModuleOtherNetwork.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

public enum OnDemandModuleOtherNetwork: String, Sendable, Codable, CaseIterable {
    case mobile = "mobile"
    case ethernet = "ethernet"
}
