//
// OpenVPNPullMask.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

/** Settings that can be pulled from server. */
public enum OpenVPNPullMask: String, Sendable, Codable, CaseIterable {
    /// Routes and gateways.
    case routes = "routes"
    /// DNS settings.
    case dns = "dns"
    /// Proxy settings.
    case proxy = "proxy"
}
