//
// OpenVPNObfuscationMethodObfuscate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

public struct OpenVPNObfuscationMethodObfuscate: Sendable, Codable, Hashable {

    public enum ModelType: String, Sendable, Codable, CaseIterable {
        case obfuscate = "obfuscate"
    }
    public var type: ModelType
    public var mask: SecureData

    public init(type: ModelType, mask: SecureData) {
        self.type = type
        self.mask = mask
    }
}

