//
// OpenVPNCredentialsOTPMethod.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

public enum OpenVPNCredentialsOTPMethod: String, Sendable, Codable, CaseIterable {
    case none = "none"
    case append = "append"
    case encode = "encode"
}
