//
// OpenVPNCompressionAlgorithm.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

/** Defines the type of compression algorithm. */
public enum OpenVPNCompressionAlgorithm: Int, Sendable, Codable, CaseIterable {
    case disabled = 0
    case LZO = 1
    case other = 2
}
