//
// OpenVPNModule.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

/** A connection module providing an OpenVPN connection. */
public struct OpenVPNModule: Sendable, Codable, Hashable {

    public var id: UniqueID
    public var configuration: OpenVPNConfiguration?
    public var credentials: OpenVPNCredentials?
    public var requiresInteractiveCredentials: Bool?

    public init(id: UniqueID, configuration: OpenVPNConfiguration? = nil, credentials: OpenVPNCredentials? = nil, requiresInteractiveCredentials: Bool? = nil) {
        self.id = id
        self.configuration = configuration
        self.credentials = credentials
        self.requiresInteractiveCredentials = requiresInteractiveCredentials
    }
}

