//
// OpenVPNStaticKey.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

/** Represents an OpenVPN static key file (as generated with --genkey) */
public struct OpenVPNStaticKey: Sendable, Codable, Hashable {

    public var data: SecureData
    public var dir: OpenVPNStaticKeyDirection?

    public init(data: SecureData, dir: OpenVPNStaticKeyDirection? = nil) {
        self.data = data
        self.dir = dir
    }
}

