//
// OpenVPNTLSWrap.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

/** Holds parameters for TLS wrapping. */
public struct OpenVPNTLSWrap: Sendable, Codable, Hashable {

    /** The wrapping strategy. */
    public var strategy: OpenVPNTLSWrapStrategy
    /** The static encryption key. */
    public var key: OpenVPNStaticKey
    /** The wrapped client key appended to initial tls-crypt-v2 packets. */
    public var wrappedKey: SecureData?

    public init(strategy: OpenVPNTLSWrapStrategy, key: OpenVPNStaticKey, wrappedKey: SecureData? = nil) {
        self.strategy = strategy
        self.key = key
        self.wrappedKey = wrappedKey
    }
}

