//
// ParseErrorInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

public struct ParseErrorInfo: Sendable, Codable, Hashable {

    public var name: String
    public var details: String

    public init(name: String, details: String) {
        self.name = name
        self.details = details
    }
}

