//
// PartoutErrorCode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

public enum PartoutErrorCode: String, Sendable, Codable, CaseIterable {
    /// Authentication failure.
    case authentication = "authentication"
    /// Response is cached.
    case cached = "cached"
    /// Crypto error.
    case crypto = "crypto"
    /// Decoding error.
    case decoding = "decoding"
    /// DNS resolution failure.
    case dnsFailure = "dnsFailure"
    /// Encoding error.
    case encoding = "encoding"
    /// No more endpoints available to try.
    case exhaustedEndpoints = "exhaustedEndpoints"
    /// File descriptor is not available.
    case fdUnavailable = "fdUnavailable"
    /// Some modules are incompatible (`userInfo` is an array of incompatible ``Module``).
    case incompatibleModules = "incompatibleModules"
    /// A module is incomplete (`userInfo` is the incomplete ``ModuleBuilder`` ID).
    case incompleteModule = "incompleteModule"
    /// Invalid field.
    case invalidField = "invalidField"
    /// Invalid value.
    case invalidValue = "invalidValue"
    /// I/O failure.
    case ioFailure = "ioFailure"
    /// Unable to add keychain item.
    case keychainAddItem = "keychainAddItem"
    /// Keychain item not found.
    case keychainItemNotFound = "keychainItemNotFound"
    /// Link device is not active.
    case linkNotActive = "linkNotActive"
    /// Network changed.
    case networkChanged = "networkChanged"
    /// Network is unreachable.
    case networkUnreachable = "networkUnreachable"
    /// The profile has no active modules.
    case noActiveModules = "noActiveModules"
    /// The profile has non-final modules that must be resolved to final modules first.
    case nonFinalModules = "nonFinalModules"
    /// Entity not found.
    case notFound = "notFound"
    /// Compression settings mismatch.
    case openVPNCompressionMismatch = "OpenVPN.compressionMismatch"
    /// Connection failure.
    case openVPNConnectionFailure = "OpenVPN.connectionFailure"
    /// No routing configuration.
    case openVPNNoRouting = "OpenVPN.noRouting"
    /// One-time password is required.
    case openVPNOTPRequired = "OpenVPN.otpRequired"
    /// Passphrase is required.
    case openVPNPassphraseRequired = "OpenVPN.passphraseRequired"
    /// Authentication can be retried.
    case openVPNRecoverableAuthentication = "OpenVPN.recoverableAuthentication"
    /// Server requested shutdown.
    case openVPNServerShutdown = "OpenVPN.serverShutdown"
    /// TLS failure.
    case openVPNTLSFailure = "OpenVPN.tlsFailure"
    /// Algorithm is unsupported.
    case openVPNUnsupportedAlgorithm = "OpenVPN.unsupportedAlgorithm"
    /// Compression setting is unsupported.
    case openVPNUnsupportedCompression = "OpenVPN.unsupportedCompression"
    /// Option is unsupported.
    case openVPNUnsupportedOption = "OpenVPN.unsupportedOption"
    /// Operation cancelled or unauthorized.
    case operationCancelled = "operationCancelled"
    /// Memory allocation failed.
    case outOfMemory = "outOfMemory"
    /// Parsing error.
    case parsing = "parsing"
    /// A passphrase is required.
    case passphraseRequired = "passphraseRequired"
    /// A required object was released prematurely.
    case releasedObject = "releasedObject"
    /// Missing a required implementation.
    case requiredImplementation = "requiredImplementation"
    /// An exception was raised during a script execution.
    case scriptException = "scriptException"
    /// Native sockets could not be configured.
    case socketConfiguration = "socketConfiguration"
    /// Operation timed out.
    case timeout = "timeout"
    /// TUN device is not active.
    case tunNotActive = "tunNotActive"
    /// TUN device is not available for I/O.
    case tunNotAvailable = "tunNotAvailable"
    /// Module type is unexpected
    case unexpectedModuleType = "unexpectedModuleType"
    /// Generic failure.
    case unhandled = "unhandled"
    /// Module content is unknown for the importer.
    case unknownImportedModule = "unknownImportedModule"
    /// Module handler is unknown.
    case unknownModuleHandler = "unknownModuleHandler"
    /// Configuration has no peers.
    case wireGuardEmptyPeers = "WireGuard.emptyPeers"
}
