//
// Route.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

/** Represents a route in the routing table. */
public struct Route: Sendable, Codable, Hashable {

    /** The destination subnet or `nil` if default. */
    public var destination: Subnet?
    /** The address of the gateway (falls back to global gateway). */
    public var gateway: Address?

    public init(destination: Subnet? = nil, gateway: Address? = nil) {
        self.destination = destination
        self.gateway = gateway
    }
}

