//
// SocketType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

/** A socket type between UDP and TCP. */
public enum SocketType: String, Sendable, Codable, CaseIterable {
    /// UDP socket type.
    case udp = "UDP"
    /// TCP socket type.
    case tcp = "TCP"
}
