//
// TaggedModuleCustom.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

public struct TaggedModuleCustom: Sendable, Codable, Hashable {

    public enum ModelType: String, Sendable, Codable, CaseIterable {
        case custom = "Custom"
    }
    public var type: ModelType
    public var value: CustomModule

    public init(type: ModelType, value: CustomModule) {
        self.type = type
        self.value = value
    }
}

