//
// TaggedModuleWireGuard.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

public struct TaggedModuleWireGuard: Sendable, Codable, Hashable {

    public enum ModelType: String, Sendable, Codable, CaseIterable {
        case wireGuard = "WireGuard"
    }
    public var type: ModelType
    public var value: WireGuardModule

    public init(type: ModelType, value: WireGuardModule) {
        self.type = type
        self.value = value
    }
}

