//
// TaggedModuleDNS.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

public struct TaggedModuleDNS: Sendable, Codable, Hashable {

    public enum ModelType: String, Sendable, Codable, CaseIterable {
        case dns = "DNS"
    }
    public var type: ModelType
    public var value: DNSModule

    public init(type: ModelType, value: DNSModule) {
        self.type = type
        self.value = value
    }
}

