//
// TaggedModuleOnDemand.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

public struct TaggedModuleOnDemand: Sendable, Codable, Hashable {

    public enum ModelType: String, Sendable, Codable, CaseIterable {
        case onDemand = "OnDemand"
    }
    public var type: ModelType
    public var value: OnDemandModule

    public init(type: ModelType, value: OnDemandModule) {
        self.type = type
        self.value = value
    }
}

