//
// TaggedProfile.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

/** A codable wrapper for a profile with all known modules. */
public struct TaggedProfile: Sendable, Codable, Hashable {
    public var version: Int?
    public var id: UniqueID
    public var name: String
    public var modules: [TaggedModule]
    public var activeModulesIds: Set<UniqueID>
    public var behavior: ProfileBehavior?
    public var userInfo: JSON?

    public init(version: Int? = nil, id: UniqueID, name: String, modules: [TaggedModule], activeModulesIds: Set<UniqueID>, behavior: ProfileBehavior? = nil, userInfo: JSON? = nil) {
        self.version = version
        self.id = id
        self.name = name
        self.modules = modules
        self.activeModulesIds = activeModulesIds
        self.behavior = behavior
        self.userInfo = userInfo
    }
}

