//
// TaggedModuleIP.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

public struct TaggedModuleIP: Sendable, Codable, Hashable {

    public enum ModelType: String, Sendable, Codable, CaseIterable {
        case ip = "IP"
    }
    public var type: ModelType
    public var value: IPModule

    public init(type: ModelType, value: IPModule) {
        self.type = type
        self.value = value
    }
}

