//
// TunnelControllerOptions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

/** Common options to give to ``TunnelController``. */
public struct TunnelControllerOptions: Sendable, Codable, Hashable {

    public var dnsFallbackServers: [String]
    public var logsSnapshots: Bool

    public init(dnsFallbackServers: [String], logsSnapshots: Bool) {
        self.dnsFallbackServers = dnsFallbackServers
        self.logsSnapshots = logsSnapshots
    }
}

