//
// TunnelSnapshot.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

/** Returns a tunnel-specific snapshot of a ``Profile``. */
public struct TunnelSnapshot: Sendable, Codable, Hashable {

    public var id: UniqueID
    public var isEnabled: Bool
    public var status: TunnelStatus
    public var onDemand: Bool
    public var environment: TunnelSnapshotEnvironment?

    public init(id: UniqueID, isEnabled: Bool, status: TunnelStatus, onDemand: Bool, environment: TunnelSnapshotEnvironment? = nil) {
        self.id = id
        self.isEnabled = isEnabled
        self.status = status
        self.onDemand = onDemand
        self.environment = environment
    }
}

