//
// TunnelSnapshotEnvironment.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

public struct TunnelSnapshotEnvironment: Sendable, Codable, Hashable {

    public var connectionStatus: ConnectionStatus
    public var dataCount: DataCount
    public var lastErrorCode: String?

    public init(connectionStatus: ConnectionStatus, dataCount: DataCount, lastErrorCode: String? = nil) {
        self.connectionStatus = connectionStatus
        self.dataCount = dataCount
        self.lastErrorCode = lastErrorCode
    }
}

