//
// TunnelStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

/** The status of a ``Tunnel``. */
public enum TunnelStatus: String, Sendable, Codable, CaseIterable {
    case inactive = "inactive"
    case activating = "activating"
    case active = "active"
    case deactivating = "deactivating"
}
