//
// WireGuardConfiguration.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

/** Represents a WireGuard configuration. */
public struct WireGuardConfiguration: Sendable, Codable, Hashable {

    /** The local interface. */
    public var interface: WireGuardLocalInterface
    /** The peers. */
    public var peers: [WireGuardRemoteInterface]

    public init(interface: WireGuardLocalInterface, peers: [WireGuardRemoteInterface]) {
        self.interface = interface
        self.peers = peers
    }
}

