//
// WireGuardRemoteInterface.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

/** The parameters of the remote interface. */
public struct WireGuardRemoteInterface: Sendable, Codable, Hashable {

    /** The endpoint public key. */
    public var publicKey: WireGuardKey
    /** The optional endpoint pre-shared key. */
    public var preSharedKey: WireGuardKey?
    /** The optional endpoint. */
    public var endpoint: Endpoint?
    /** The list of allowed subnets. */
    public var allowedIPs: [Subnet]
    /** The keep-alive interval in seconds. */
    public var keepAlive: ModelUInt16?

    public init(publicKey: WireGuardKey, preSharedKey: WireGuardKey? = nil, endpoint: Endpoint? = nil, allowedIPs: [Subnet], keepAlive: ModelUInt16? = nil) {
        self.publicKey = publicKey
        self.preSharedKey = preSharedKey
        self.endpoint = endpoint
        self.allowedIPs = allowedIPs
        self.keepAlive = keepAlive
    }
}

